app             = "ahooooy"
primary_region  = "bom"
kill_signal     = "SIGINT"
kill_timeout    = 5
swap_size_mb    = 256

[[mounts]]
  volume = "ahooooy_vol"
  path   = "/ahooooy"

[[vm]]
  size = "shared-cpu-1x"

[[services]]
  internal_port = 3000

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]
    protocol = "tcp"

  [[services.ports]]
    port     = 80
    handlers = ["http"]
    protocol = "tcp"

[env]
  APP = "ahooooy"

[[restart]]
  policy = "always"
